"""
Data schemas and state definitions for PatchPilot multi-agent workflows.
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class IssueFinding(BaseModel):
    """An individual flaw or vulnerability identified by the Auditor Agent."""
    title: str
    severity: str = "MEDIUM"  # LOW, MEDIUM, HIGH, CRITICAL
    line_number: Optional[int] = None
    description: str
    cwe_id: Optional[str] = None
    suggested_fix: str


class AuditReport(BaseModel):
    """Aggregated findings produced by the Auditor Agent."""
    summary: str
    issues: List[IssueFinding] = Field(default_factory=list)


class SynthesizedTest(BaseModel):
    """Reproduction and regression test suite generated by Test Synthesizer Agent."""
    test_code: str
    rationale: str


class PatchProposal(BaseModel):
    """Code modification proposed by Patch Generator or Reflector Agent."""
    patch_explanation: str
    patched_code: str


class ExecutionStep(BaseModel):
    """Log of a sandbox execution attempt during self-healing."""
    attempt: int
    passed: bool
    duration_seconds: float
    feedback: str


class AgentSessionState(BaseModel):
    """Full state of a PatchPilot review and self-healing session."""
    filepath: str
    original_code: str
    ast_summary: str
    audit_report: Optional[AuditReport] = None
    synthesized_test: Optional[SynthesizedTest] = None
    current_patch: Optional[PatchProposal] = None
    is_verified: bool = False
    repair_attempts: int = 0
    history: List[ExecutionStep] = Field(default_factory=list)
